### ISSUE TITLE
swapoff call needs second argument

### ISSUE THREAD

**Issue by cperciva** [qemu-bsd-user/qemu-bsd-user#22]
The `swapoff(2)` syscall takes two arguments -- the name of the device or file, and a set of flags.  This is breaking the build:

https://github.com/qemu-bsd-user/qemu-bsd-user/blob/aa38bbc4943eb8dcd605aef37d5d86940bdcdca3/bsd-user/bsd-file.h#L1119

Adding a `, 0` (i.e. not setting the SWAPOFF_FORCE flag) to the `swapoff` call fixes the build.

**Comment by bsdimp** [comment]
Fixed in both 3.1 rebase and in blitz current code
