### ISSUE TITLE
Can't run Linux binaries

### ISSUE THREAD

**Issue by Zirias** [qemu-bsd-user/qemu-bsd-user#38]
Ran into the issue with `multimedia/makemkv` which needs a Linux compiler to build, it probably only affects the 6 ports listing `linux-c7-devtools` as a build dependency.

Just leaving that here with a little hope there *might* be a simple solution...

**Comment by bsdimp** [comment]
You are asking for something that's way out of scope.
bsd-user will never run linux binaries, that's what linux-user is for.
linux-user might run well enough in the linuxulator to run foreign-arch binaries... except that the binfmt stuff is somewhat imprecise in what it execs due the simplicity of its testing ability not being able to finely tell Linux and FreeBSD binaries apart. You might be able to create a wrapper that will look at the binary to be execed and then exec the appropriate bsd-user or linux-user for the binary.
