### ISSUE TITLE
should qemu-user-static run on all FreeBSD Tier 1 platforms? 

### ISSUE THREAD

**Issue by igalic** [qemu-bsd-user/qemu-bsd-user#43]
right now, qemu-user-static doesn't run on aarch64 (arm64).

aarch64 is a Tier 1 platform.
should qemu-user-static run on all FreeBSD Tier 1 platforms?

**Comment by bsdimp** [comment]
What is the error? Tier 1 has no relevance here: if it doesn't work, someone will have to fix it that has time. That's unlikely to be me.

**Comment by igalic** [comment]
```
ONLY_FOR_ARCHS=		amd64 powerpc powerpc64
```
has been set like this since the beginning of the port:

https://github.com/freebsd/freebsd-ports/blame/main/emulators/qemu-user-static/Makefile#L15
https://github.com/freebsd/freebsd-ports/blame/main/emulators/qemu-user-static-devel/Makefile#L15

maybe @kevans91 knows more

**Comment by bsdimp** [comment]
```
../meson.build:3470:6: ERROR: Include dir bsd-user/host/aarch64 does not exist.
```
Doesn't even build. You'll need to write host/aarch64 support if you want it. Next time please try to build it yourself before you ask, since I wasted 15 minutes this morning getting a aarch64 machine setup enough to build this.
